### ISSUE TITLE
S2325 should not fire is the method is decorated with TestMethodAttribute

### ISSUE THREAD

**Issue by jabbera** [SonarSource/sonarlint-vs#139]
S2325 - Methods and properties that don't access instance data should be static

should not fire if the method is a test method and decorated as such. (There are probably other attributes this holds for as well) If one were to mark the method as static the test would not run.

**Comment by dbolkensteyn** [comment]
Thanks Mike for this feedback. We've received the same from multiple sources, and after having carefully thought about all possible cases - we decided in the end to drop the S2325 rule altogether. See #65 for details.
