### ISSUE TITLE
Add codefix for empty statement rule (S1116)

### ISSUE THREAD

**Issue by tvsonar** [SonarSource/sonarlint-vs#141]

**Comment by dbolkensteyn** [comment]
This isn't working as expected - the bulk fixer is broken

**Comment by tvsonar** [comment]
@dbolkensteyn I added a new commit into this PR, now the bulk fixer works as expected. I took this as an example: https://github.com/code-cracker/code-cracker/blob/df7aa2929345ed65c5a8f964a7c9d97b04ad5033/src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedFixAllProvider.cs

**Comment by dbolkensteyn** [comment]
Roslyn's original `BatchFixAllProvider` code can be found here: https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs
