### ISSUE TITLE
Don't report issues on files containing generated code attributes

### ISSUE THREAD

**Issue by dbolkensteyn** [SonarSource/sonarlint-vs#164]
This issue relates to #85 and pushes it one level further: Instead of looking only at the filename to know whether or not the file is generated (and should therefore be excluded), we also will look at the file contents.

Specifically, the idea is to look for the usage of the following attributes - which are typically used to indicate generated code:
* `[GeneratedCode]` - https://msdn.microsoft.com/en-us/library/system.codedom.compiler.generatedcodeattribute(v=vs.110).aspx
* `[DebuggerNonUserCode]` - https://msdn.microsoft.com/en-us/library/system.diagnostics.debuggernonusercodeattribute(v=vs.110).aspx
* `[ExcludeFromCodeCoverage]` - https://msdn.microsoft.com/en-us/library/system.diagnostics.codeanalysis.excludefromcodecoverageattribute(v=vs.110).aspx
* `[CompilerGenerated]` - https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.compilergeneratedattribute(v=vs.110).aspx

@fmallet This can quite easily be implemented in SonarLint VS. However, this one would be a bit harder to implement on the MSBuild Runner side.

So far we have seen one project, Akka.NET, which has files not ending with generated extensions, but that actually contain these attributes.

**Comment by tvsonar** [comment]
I found the following cases that should be covered
* from a .cshtml file you can generate the .cs with the [_RazorGenerator_](http://blog.davidebbo.com/2011/06/precompile-your-mvc-views-using.html), and the .cs has the `<auto-generated>` comment in it and the `GeneratedCodeAttribute` 
* Resource files are not necessarily generated as a .Designer.cs file, but as a .cs, so by file name they are not excluded. They contain the `GeneratedCodeAttribute`.

**Comment by ngm** [comment]
Just for reference, the [T4MVC](https://github.com/T4MVC/T4MVC) project is another case where this occurs.  It generates a T4MVC.cs file, with the generated code marked with `GeneratedCodeAttribute` and `DebuggerNonUseCode`.

**Comment by dbolkensteyn** [comment]
Thanks @ngm , this issue is supposed to be fixed in SonarLint VS 1.3.0 - please create a new issue if you still experience false positives on generated code.
