### ISSUE TITLE
Add codefix for S3235 (redundant parentheses)

### ISSUE THREAD

**Issue by tvsonar** [SonarSource/sonarlint-vs#165]

**Comment by dbolkensteyn** [comment]
to check: do we really have to uninstall/install the extension to see the codefixes?

**Comment by tvsonar** [comment]
@dbolkensteyn I've created a separate issue for this question: #169

**Comment by dbolkensteyn** [comment]
LGTM - but there is a merge conflict & AppVeyor isn't runing :)
