### ISSUE TITLE
Rule idea: Preserve exception stacktrackes by properly rethrowing them (FxCop CA2200)

### ISSUE THREAD

**Issue by dbolkensteyn** [SonarSource/sonarlint-vs#205]
See https://msdn.microsoft.com/en-us/library/ms182363.aspx

This complements #173

**Comment by tvsonar** [comment]
@dbolkensteyn It seems, that this is already implemented in Roslyn: https://github.com/dotnet/roslyn/blob/0382e3e3fc543fc483090bff3ab1eaae39dfb4d9/src/Diagnostics/FxCop/CSharp/Usage/CSharpCA2200DiagnosticAnalyzer.cs

**Comment by dbolkensteyn** [comment]
@tvsonar I didn't get issues in the IDE yesterday - do you? Blaming that file shows it has been written in May 2014.

**Comment by tvsonar** [comment]
Duplicates #672
