### ISSUE TITLE
S1172 should not report on event handlers

### ISSUE THREAD

**Issue by jessehouwing** [SonarSource/sonarlint-vs#211]
S1172 should not flag unused members if they are part of an interface method or when they are  passed to a delegate/eventhandler.

Classic example of this is the (sender, event) passed to an Event handling function. Many people don't use the sender and often not even the event, this is not really a problem.

Alternative syntax, such as += (s,e) => MethodWithoutParameters(); works, but had the problem that unsubscribing from the event requires us to store the delegate so that we can use it in the -= call later on.

**Comment by tvsonar** [comment]
@jessehouwing I see your point with the event handlers. I've added a [comment](http://stackoverflow.com/questions/32078974/sonarlint-rule-s1172-unused-method-parameters-should-be-removed-and-eventhandl#comment52071559_32078974) to the [SO](http://stackoverflow.com/questions/32078974/sonarlint-rule-s1172-unused-method-parameters-should-be-removed-and-eventhandl) question where the discussion started.

Here is the relevant part: My feeling is that if you don't need the `sender` and the `EventArgs` at all, then you could use a custom delegate which doesn't have those. But this only works if you control the type of the event. Do you think this goes against event handling best practices?

Additionally: Can you provide some code samples for the false positives with interface implementations? This rule should not trigger an issue, if the method is `abstract`, `virtual`, `override`, or if it is an interface implementation.

**Comment by njannink** [comment]
Its a design guideline that event delegates always should be (derived) of the type EventHandler. So that means you will always get the sender and EventArgs. [MSDN](https://msdn.microsoft.com/en-us/library/vstudio/ms229011(v=vs.100).aspx)

So even tho the subscribers don't use those parameters all events in the .Net framework are build using this paradigm and so by my opinion SonarLint should be able to handle this. 

I think Resharper correctly recognises event handling methods and ignores the unused parameters of these.

**Comment by tvsonar** [comment]
Thanks for the MSDN link. 

It seems to me that Resharper does at least two things differently
* doesn't report on any non-`private` method
* for `private` methods it is checking if the method is assigned to a anything (local variable, field, event, ...)

These reduce the number of false positives, but also introduce a lot of false negatives. Instead, I would probably go with identifying event handler method signatures.

**Comment by jessehouwing** [comment]
Thanks for chiming in with the design guidelines. That's what I'd have done. I'll have to look up the case where it triggered on an interface variable. I've refactored that codebase quite a bit over the last week.

**Comment by jessehouwing** [comment]
When conforming to a delegate signature that's outside of the scope of the solution, don't log a warning, but you may provide an informational item to check out the delegate structure at the source.

When inheriting from EventHandler, don't warn ever. (See design guidelines). Don't even log an informational item. You may even want to introduce a rule which enforces this design guideline.

Make sure that null checks are not the only reference, right now adding simple argument null checks defeats the warning ;). This may be a hairy flow check to implement, as the nullness may be used for other logic as well:

        private Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
        {
            if (sender == null)
            {
                throw new ArgumentNullException(nameof(sender));
            }

**Comment by njannink** [comment]
the above example is actually a bad one. Since an eventhandler should return void according to the guidelines.

**Comment by jessehouwing** [comment]
It's a standard event from AppDomain.ResolveAssembly

There are a few in the base class library.

**Comment by njannink** [comment]
Yes its wellknown that Microsoft doesn't comply to its own guidelines :)
