### ISSUE TITLE
S2930 call to dispose is not detected when using ?. syntax

### ISSUE THREAD

**Issue by jessehouwing** [SonarSource/sonarlint-vs#214]
In this code S2930 still triggers, while, if `tfs` is `null` it doesn't make sense to dispose it.

        public void Dispose()
        {
            this.Dispose(true);
            GC.SuppressFinalize(this);
        }

        protected void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.tfs?.Dispose();
            }
        }

While using the old style syntax suggests to use null propagation:

        protected void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (this.tfs != null)
                {
                    this.tfs.Dispose();
                }
            }
        }

**Comment by tvsonar** [comment]
This issue duplicates #202. (And will be resolved in the upcoming 1.2.0 version)
