### ISSUE TITLE
Fix the codefix for S1940 (inverted boolean check)

### ISSUE THREAD

**Issue by tvsonar** [SonarSource/sonarlint-vs#229]
The current implementation of the codefix always removes the parentheses, but in some cases this can't be done.

Related to #148 

For example: `var a = !!(args.Length == 0)` will get fixed into `!args.Length != 0` which then doesn't compile.

With dynamics, it should be possible to get programs that still compile but whose meaning will change, as in:
```
dynamic foo = null;
var a = !(foo == 0) + 3;
```

that will become:
```
var a = foo != 0 + 3
```

which will be evaluated not as `(foo != 0) + 3` as originally intended, but as `foo != (0 + 3)`

**Comment by dbolkensteyn** [comment]
@tvsonar you probably want to mention the cases in the issue itself - else you need to fetch them from #148, then go to its Pull Request, which is painful.
