### ISSUE TITLE
Parallel collections should not be maintained

### ISSUE THREAD

**Issue by tvsonar** [SonarSource/sonarlint-vs#362]
https://jira.sonarsource.com/browse/RSPEC-3221

http://codeblog.jonskeet.uk/2014/06/03/anti-pattern-parallel-collections/

**Comment by tvsonar** [comment]
We'll come back to this when we can enable it by default.

**Comment by dbolkensteyn** [comment]
This rule's idea was good, and the implementation was done, but unfortunately there were too many "good exceptions" to this rule to make it valuable.
