### ISSUE TITLE
S1940 should not report on implementations of operator != overloads

### ISSUE THREAD

**Issue by OsirisTerje** [SonarSource/sonarlint-vs#381]
Rule S1940 reports on the correct implementation of an != operator.  THis is the one case where this good rule do not apply.
![image](https://cloud.githubusercontent.com/assets/203432/9566901/cdba9584-4f18-11e5-9ca1-e211a4e7ce8f.png)

Ref.: https://msdn.microsoft.com/en-US/library/ms173147(v=vs.80).aspx

**Comment by tvsonar** [comment]
Thanks @OsirisTerje for reporting this. We've scheduled it into the current sprint.

**Comment by dbolkensteyn** [comment]
LGTM
