### ISSUE TITLE
S2123 reacts on fields and properties

### ISSUE THREAD

**Issue by OsirisTerje** [SonarSource/sonarlint-vs#382]
Rule 2123 is valuable for local variables, but should not trigger for fields and properties that are accessible later. 
The example below show one case:
![image](https://cloud.githubusercontent.com/assets/203432/9567121/9cc3ed70-4f1f-11e5-9f75-072e4e6dbcb1.png)
(If counter is made into a property, we get the same result.)

If, however, the NextIndex method is made into an expression body, the warning disappears. 
![image](https://cloud.githubusercontent.com/assets/203432/9567126/da9f0ff8-4f1f-11e5-9064-030314a0e17a.png)

Also, what is strange is that pressing the "Show potential fixes" doesn't show anything from this rule, but do show fixes from another rule (not Sonar).  I am not sure if this is Sonar or Roslyn, but should be looked at. 

The effect of pressing that is:
![image](https://cloud.githubusercontent.com/assets/203432/9567133/23580574-4f20-11e5-9967-4a5c4dc041f9.png)

**Comment by tvsonar** [comment]
Thanks @OsirisTerje, I've created #384 for the false negative

**Comment by dbolkensteyn** [comment]
LGTM
