### ISSUE TITLE
Improve the metadata of S2760 not to show it as a bug

### ISSUE THREAD

**Issue by OsirisTerje** [SonarSource/sonarlint-vs#383]
Rule S2760 seems to miss that intermediate methods may affect a condition check.
The rule says that:
![image](https://cloud.githubusercontent.com/assets/203432/9567254/41e979ce-4f24-11e5-8a97-b5149f6028f6.png)
But the code in questions is like:
![image](https://cloud.githubusercontent.com/assets/203432/9567257/56ed223a-4f24-11e5-9ee9-334b30458509.png)
Both Position and Length are properties of the file object, which may have been changed by the call in (1), so the test in (2) is not "sequential".

**Comment by tvsonar** [comment]
@OsirisTerje We had a discussion on this internally and decided to keep the implementation as is. We'll change the rule's category from "bug" to "clumsy, suspicious", and disable the rule by default. You can check out these meta information changes here: https://jira.sonarsource.com/browse/RSPEC-2760, and of course it will be reflected on http://vs.sonarlint.org/rules/index.html#ruleId=S2760 as well.

if you have only these two consecutive checks you could rewrite them like the following:
```
if (file.Position != file.Length)
{
  Read...
  if (file.Position != file.Length)
  {
    ...
  }
}
```
This way if you were already at the end of the file, you won't check it twice. But I can understand if you don't want to do this.
