### ISSUE TITLE
Codefix fo S1125 should add parenthesis if it negates complex conditions

### ISSUE THREAD

**Issue by tvsonar** [SonarSource/sonarlint-vs#386]
Negating the condition without adding parenthesis on complex conditions might change the program's meaning, e.g.:

```
x || booleanVariable ? false : true
```

gets rewritten into:
```
!x || booleanVariable
```

which is not equivalent to:
```
!(x || booleanVariable)
```

**Comment by dbolkensteyn** [comment]
LGTM
