### ISSUE TITLE
S3052 Decimals initialized to non-zero reported as default value (false positive)

### ISSUE THREAD

**Issue by jbfraser1** [SonarSource/sonarlint-vs#414]
S3052 generates a warning for code such as:

        private const decimal BandFractionalWidth = .2m;

Warning	S3052	Remove this initialization to "BandFractionalWidth", the compiler will do that for you.

**Comment by tvsonar** [comment]
@jbfraser1 Thanks for reporting this. We'll fix it in the current sprint.
