### ISSUE TITLE
S1125 should not report on nullable booleans

### ISSUE THREAD

**Issue by wimr** [SonarSource/sonarlint-vs#461]
currently, the implementation (I use C#) will also trigger for nullable booleans. (ignore the bad use of Random. Just for demo purpose)

![image](https://cloud.githubusercontent.com/assets/610620/10277200/af0c6ef2-6b54-11e5-997d-1572dbec7656.png)

This will result in code that does not compile.

**Comment by tvsonar** [comment]
@wimr Thanks for reporting this issue.
