### ISSUE TITLE
Attribute, EventArgs, and Exception type names should end with the type being extended

### ISSUE THREAD

**Issue by njannink** [SonarSource/sonarlint-vs#500]
Deriving from the following classes should also be visible in the name:

```
class MyAttribute : Attribute { }
class MyEventArgs : EventArgs { }
class MyException : Exception { }
```

Maybe there are some more examples I do not recall at the moment

**Comment by tvsonar** [comment]
@ganncamp Could you create an RSPEC for this rule idea?

**Comment by ganncamp** [comment]
Done: https://jira.sonarsource.com/browse/RSPEC-3376
