### ISSUE TITLE
S1172 shouldn't report on extension methods' "this" parameter

### ISSUE THREAD

**Issue by timadamson** [SonarSource/sonarlint-vs#509]
SonarLint complains about 'this' parameters not being used in extension methods. 

For example it's quite common practice for HtmlHelper extension methods to not use the object instance as the helper method is only attached to the object as a convenience.

**Comment by tvsonar** [comment]
@timadamson thanks for reporting this. We're having a discussion internally if we're adding this exception to the rule. From a technical point this is not a false positive, but we see that the use of `HtmlHelper` is a convention that should be considered. 

Do you know similar cases?

**Comment by timadamson** [comment]
Not off the top of my head.

Extension methods where the extended object isn't referenced could be a separate case, they're more similar to instance methods that can be made static which in ReSharper is considered info/message level. A separate rule could be disabled without losing the checking of other unused parameters.

**Comment by dbolkensteyn** [comment]
@tvsonar :+1: for @timadamson proposal to not check the `this` parameter of extension methods, and not hardcode an exception for `HtmlHelper`. The rule description should be updated to document this exception.
