### ISSUE TITLE
Expression based code fixes should not crash when the expression is an argument

### ISSUE THREAD

**Issue by tvsonar** [SonarSource/sonarlint-vs#515]
When a diagnostic is reported on an expression that expression can be an argument to a method at the same time. In the code fixes we use `FindNode`, which automatically takes the outermost complete match, but that means taking the argument syntax instead of the expression syntax. So in these cases the `getInnermostNodeForTie: true` should be specified.

**Comment by dbolkensteyn** [comment]
@tvsonar this issue sounds quite technical - does it have any impact on the user?

**Comment by tvsonar** [comment]
Yes, it has. Previously if we reported an issue on an expression, and that expression happened to be in an argument, then the codefix found the `ArgumentSyntax`, and failed to cast it.

**Comment by dbolkensteyn** [comment]
Ok, it is best to make this explicit from the issue itself @tvsonar - they should be as end user oriented as possible
