### ISSUE TITLE
Reduce the number of issues reported by S125

### ISSUE THREAD

**Issue by blairmcg** [SonarSource/sonarlint-vs#519]
S125 complains too much in SonarLint 1.3.0:
- it fires on code-like content in plain text (if the whole line is not parseable as a statement/expression, then it should not be assumed to contain code)
- it should never fire on summary comments. Any code included in these is very likely provided by way of example, and is not commented out code
- it should only fire once for any uninterrupted block of comments, not once for each apparent block of code separated by either blank lines or text, or embedded comments
 
Here is an example where the rule files, which is both a summary comment, and contains no code
    /// <summary>
    /// The C++ access level for a member function, e.g. private
    /// </summary>

If I have a block of commented out code like this, with blank lines, I get 3 occurrences of S125 reported:

S125    //Debug.Assert(this.MemberTypeName != null == storage.HasFlag(StorageClass.Member));
            //
S125   //if (storage.HasFlag(StorageClass.Member))
            //{
            //    output |= this.MemberTypeName.DisplayOn(builder, s);
            //    builder.Append(CppNameBuilder.NameSeparator);
            //    // Not trailing space wanted
S125    //    output = false;
            //}

**Comment by tvsonar** [comment]
@blairmcg I reduced the number of issues by reporting only one for consecutive line comments with optionally empty lines between them. Also, for multiline comments we are reporting at most one issue now. 

Summary comments were already excluded from the analysis, so I haven't changed anything on those.

I think trying to parse each line as a statement or expression won't work, it will result in too many false negatives. 

This modification will be shipped with version 1.5.0. Can you get back to us after the release if you still experience annoying issues?
