### ISSUE TITLE
S1313 should not report on string literal "::"

### ISSUE THREAD

**Issue by blairmcg** [SonarSource/sonarlint-vs#520]
public static readonly string NameSeparator = "::";
causes
      Warning	S1313	Make this IP :: address configurable.....

**Comment by tvsonar** [comment]
@blairmcg Thank you for raising this issue. 
We've added an exception for "::", which is actually a valid IPv6 address (with the expanded value "0:0:0:0:0:0:0:0", which is the IPv6 unspecified address).
