### ISSUE TITLE
S3249 should not report on reference equality guard conditions in Equals

### ISSUE THREAD

**Issue by blairmcg** [SonarSource/sonarlint-vs#521]
S3249 fires for an Equals implementation that calls base.Equals where the nearest overridden implementation is that in object. The help states "no two Objects that use those base methods will ever be equal", but this is incorrect if the argument to Equals is the same object as the receiver. i.e. x.Equals(x), then the two objects are one and the same and are equal. 
Calling base.Equals and landing in object is the same as calling ReferenceEquals, and either can be a useful optimization as a guard clause at the top before performing more expensive value comparisons. I think if you believe this rule has value, then it should be more careful to differentiate between "base.Equals(x) && <class specific conditions)" (where calling base.Equals would be an error, since then only the same objects would ever be equal) and "base.Equals(x) || <class specific conditions>" where it isn't actually incorrect.
The rule could advise replacing the call with ReferenceEquals in the 2nd case, but not to remove it as although semantics should be preserved (if the Equals implementation is correct), removing it may have an adverse performance impact in some code.

Here's an example:

        public override bool Equals(object obj)
        {
            if (base.Equals(obj))              <------------
            {
                return true;
            }

            NameNode otherName = obj as NameNode;
            return otherName != null && otherName.Name == this.Name;
        }
Warning	S3249	Remove this "base" call.	

rather than removing the guard clause entirely, this should be rewritten as:

        public override bool Equals(object obj)
        {
            if (object.ReferenceEquals(obj, this))
            {
                return true;
            }
...

**Comment by tvsonar** [comment]
We decided to recognize the `if(base.Equals(other)) return true;` and add an exception for this. And we also added #621 to complement this rule.
