### ISSUE TITLE
S1699 should not report on virtual methods called on other instances

### ISSUE THREAD

**Issue by huserben** [SonarSource/sonarlint-vs#569]
Hi there
I discovered a bug whithin the rule S1699.
When you have a copy constructor which takes an instance of the class and calls a method that is virtual on this instance, it reports that this is not allowed. But calling these methods on an already initialized instance should be allowed.

Example:
protected abstract class A 
{
   public A(A otherInstanceOfA)
   {
      // Gets reported as violation of S1699
      otherInstanceOfA.DoSomething();
   }
    public virtual void DoSomething(){}
}

**Comment by tvsonar** [comment]
Thanks for reporting this issue @huserben
