### ISSUE TITLE
Separate C# and VB.NET analyzers to their own assemblies

### ISSUE THREAD

**Issue by tvsonar** [SonarSource/sonarlint-vs#591]
We reference both CodeAnalysis DLLs from our nuget package. But only the required one is loaded in VS. So if you have only C# projects the VB dll will not be loaded, and a MissingAnalyzer/IDE1003 warning will show up.

**Comment by dbolkensteyn** [comment]
isn't this the case now @tvsonar ?

**Comment by tvsonar** [comment]
Yes it is.
