### ISSUE TITLE
Drop the magic number rule (S109)

### ISSUE THREAD

**Issue by tvsonar** [SonarSource/sonarlint-vs#598]
It reports too many issues, and can't be enabled by default.

**Comment by kevinpdpath** [comment]
So there was no hope of fixing S109 to avoid the false positives? It doesn't seem like the task would be impossible to the point where the code should be completely removed like it was here. Is there a specific example that it considered impossible to fix?

Could the code be added back with notes about false positives and an empty Initialize method, sort of like StyleCop.Analyzers does in the following file?

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1628DocumentationTextMustBeginWithACapitalLetter.cs

**Comment by dbolkensteyn** [comment]
Thank you for this feedback @kevinpdpath 

At this stage of SonarLint VS, we'd like to put all our energy and focus on working on rules that are not controversial and that will apply to the vast majority of .NET users. We don't want yet to work on rules that will need manual tuning from end-users, nor on ones that might generate false positives.

In the future, we might give this rule another try.

Meanwhile, you can find the code of this analyzer back from the Git SCM: We use our issue tracker to track our work, and won't add "useless" unreachable code to the project.

**Comment by kevinpdpath** [comment]
Thanks for the quick reply. Are there any examples of false positives that you can provide? Since this was closed for that reason, there must have been examples. Recording those would be helpful for someone else that may want to look into fixing the rule.

I understand that you don't want clutter in your main codebase, but what about a branch? The code that generated the false positives could live there, along with failing automated tests to represent the false positives. Someone may be interested enough to submit a pull request to make some of the tests start passing.

**Comment by dbolkensteyn** [comment]
I don't remember exactly what these false positive cases where @kevinpdpath 

However a good starting place to find them back would be from: https://github.com/SonarSource/sonarlint-vs/blob/1.4.0/src/Tests/SonarLint.RulingTest/Expected/CSharp/S109.json

This is the file containing the list of issues generated (and expected) by this rule.

As you can see, it's quite a huge one, over 5 MB, much larger than most rules. This is generally a good indicator that the rule is generating way too much noise. You can look at the individual cases and decide yourself whether you believe that the code is really worth to be fixed, or whether it's a false positive.

**Comment by p3pijn** [comment]
I agree with @kevinpdpath. 
Allow me to add some feedback.

This is one of those rules I see often enforced in software project tenders (and sometimes even regulations) in The Netherlands. It is also part of the IfSQ level 2 standard for source code quality (see [http://www.ifsq.org/indicator-SPM-1.html](url) ).
In my opinion this rule is a valuable addition to help teams respond quickly to violations and prove compliance with enforced standards and regulations. These are the kind of features that make (small, but especially the larger) contractors decide to embed such tools into all software projects: to ensure compliance to market standards.
