### ISSUE TITLE
Fix missing analyzer dependencies warning with SonarLint NuGet

### ISSUE THREAD

**Issue by dbolkensteyn** [SonarSource/sonarlint-vs#611]
When using SonarLint 1.4.0 in Visual Studio 2015 Update 1, missing dependencies warnings are shown when Visual Studio is loaded with just C# or VB.NET projects, but not both.

![warnings](https://cloud.githubusercontent.com/assets/1132601/11142872/c714ba26-89f0-11e5-9064-ea8da037aa32.jpg)

The root cause is that SonarLint ships with just one assembly containing both the C# and VB.NET analyzers, and that assembly therefore depends on both the C# and VB.NET Roslyn compiler assemblies. However, Visual Studio will only load the C# Roslyn compiler assemblies (and not the VB.NET ones) when a C# project is opened.

The proper fix is to have 3 separate DLLs: a "common" one, one containing C# analyzers, and another one containing VB.NET analyzers. The NuGet package installation script should check the project's language to know which assemblies to add as analyzers.

The VSIX embed all 3 DLLs.

Thanks @jessehouwing @srivatsn for reporting this issue.

**Comment by tvsonar** [comment]
Note: this issue is not related to VS2015 Update 1.

**Comment by dbolkensteyn** [comment]
LGTM, however because of https://github.com/dotnet/roslyn/issues/6784, I was not able to get the SonarLint VS VSIX to work on Visual Studio 2015 Community Update 1 RC.

It did work on VS 2015 Enterprise Update 1 RC though.

This root cause of this failure seems to be outside of our reach, and up to the Roslyn team to fix.
