### ISSUE TITLE
"base.Equals" should not be used to check for reference equality in "Equals" override

### ISSUE THREAD

**Issue by tvsonar** [SonarSource/sonarlint-vs#621]
RSPEC: https://jira.sonarsource.com/browse/RSPEC-3397

When overriding `Equals` you can add a guard condition to return fast like this:

    public override bool Equals(object obj)
    {
        if (base.Equals(obj))              <------------
        {
            return true;
        }

        NameNode otherName = obj as NameNode;
        return otherName != null && otherName.Name == this.Name;
    }

However, when the `base.Equals` is not `object.Equals` than this is a bug, because we are not checking the current classes other fields.

**Comment by jabbera** [comment]
This may be pedantic, but I prefer:

If object.referenceequals(o1, o2))
  Return true

At the top of the class hierarchy. It's more explicit and is actually tolerant to change in the class hierarchy while just being a little less efficient. The base.equals, not so much.

**Comment by tvsonar** [comment]
@jabbera That's exactly the suggestion which will be proposed to the developer.
