### ISSUE TITLE
Group rules by meaningful categories

### ISSUE THREAD

**Issue by OsirisTerje** [SonarSource/sonarlint-vs#627]
The categories commonly used are:
![image](https://cloud.githubusercontent.com/assets/203432/11249663/94aac40e-8e28-11e5-8de8-a33948b0d896.png)

SonarLint and SonarQube is not good category name as they match the name of the ruleset. If one want to exclude the complete set, it can be nicely done using the ruleset view.  
The rules should be group into categories following the already established categories.

**Comment by tvsonar** [comment]
@OsirisTerje We can certainly do this as all our rules are categorized already for SQALE characteristics and sub-characteristics. However, if we do this change then enabling/disabling all SonarLint rules becomes less obvious, as in the ruleset editor the Namespace and Analyzer IDs (that would contain SonarLint.CSharp or SonarLint.VisualBasic) are not showing up by default. Also, the search only seems to check the Analyzer ID of the two. 

In any case, we can make this change as @fmallet already answered you by e-mail.

**Comment by OsirisTerje** [comment]
I am not sure what you mean by "Not showing up by default".  What I see when I open up the rulesset is this:
![image](https://cloud.githubusercontent.com/assets/203432/11270160/d6ea89f0-8ebc-11e5-8283-73b24fb0d0ad.png)

And the sonarlint.csharp is there.

**Comment by tvsonar** [comment]
Ahh, you are right. I don't know why I added the Analyzer ID column.

**Comment by OsirisTerje** [comment]
Just note that the Sqale characteristics and subcharacteristics doesn't seem to fully match what I showed above, and which contains areas which certainly would be of interest to a developer, e.g. Globalization, and Mobility.
