### ISSUE TITLE
S101 should not trigger for static classes who's name ends in Extensions

### ISSUE THREAD

**Issue by jessehouwing** [SonarSource/sonarlint-vs#630]
The common naming pattern for Extension methods is to create a static class, have it start with the type it wants to extend followed by "Extensions", taking this one step further, a set of methods extending an interface thus starts with INameExtensions. Even StyleCop doesn't take offence on this construct.

Side note, the error message is horrible, as it takes the whole regex into the message and can't tell me what to do to if this naming issue occurs, I need to figure out what part of the expression causes the violation.

I vote to disable this rule by default and to let people use StyleCop instead for naming related items, it is far more advanced and there is no need to have two competing rulesets from two open source projects doing the exact same thing.

**Comment by tvsonar** [comment]
@jessehouwing I see your problem, we tried to be clever, and make sure that interface names doesn't show up as class names. We'll change the Regex accordingly.

The regex will be simplified, so it won't be that difficult to check what's wrong with it.

The rule will be disabled in the next version.

**Comment by tvsonar** [comment]
Related to #645

**Comment by dbolkensteyn** [comment]
:+1: @tvsonar
