### ISSUE TITLE
Rule: Double negation operator

### ISSUE THREAD

**Issue by dbolkensteyn** [SonarSource/sonarlint-vs#64]
Replaces http://jira.sonarsource.com/browse/LINTVS-172

Using `!!` doesn't make sense, and can be safely removed.

Exception: if the negation operator is overloaded, then we shouldn't report on it. 

R# ID: *DoubleNegationOperator*

Implements: http://jira.sonarsource.com/browse/RSPEC-2761

**Comment by dbolkensteyn** [comment]
@fmallet : Pretty simple but valuable rule that might target most languages.

**Comment by dbolkensteyn** [comment]
I'm not convinced about the exception @tvsonar

**Comment by tvsonar** [comment]
@dbolkensteyn okay, I'm not adding the exception. (It is not in RSPEC either)
