### ISSUE TITLE
S2333 false positive when using xaml.cs

### ISSUE THREAD

**Issue by jmecosta** [SonarSource/sonarlint-vs#658]
lint complains that partial used in xaml.cs is gratuitos. to replicate create a ui applications and a xaml file. then go to the xaml.cs  and you get the false positive.

**Comment by tvsonar** [comment]
I can't repro this issue. In VS2015 (Update1), with the SonarLint extension, the rule seems to correctly pick up both parts of that class: ".xaml.cs" and "g.i.cs".

Are you using the nuget package or the VSIX?

**Comment by jmecosta** [comment]
i can see those in sonar web using 4.4, 
![redundant-1](https://cloud.githubusercontent.com/assets/1041352/11526336/77810df6-98e2-11e5-8208-2808a0c96885.png)

also it complains about virtual 
![redundant-2](https://cloud.githubusercontent.com/assets/1041352/11526359/9515ac1e-98e2-11e5-901f-5a3430a9d2d4.png)

**Comment by tvsonar** [comment]
This is not a SonarLint issue. SonarLint works inside Visual Studio. 

This is an issue with the SonarQube C# plugin, and it will be fixed in the upcoming release.

**Comment by jmecosta** [comment]
Ok great thanks
