### ISSUE TITLE
Rule: Method overload with optional parameter

### ISSUE THREAD

**Issue by dbolkensteyn** [SonarSource/sonarlint-vs#66]
Replaces http://jira.sonarsource.com/browse/LINTVS-180

```
void Print(string[] messages) {...}  // Noncompliant
void Print(string[] messages, string delimiter = "n") {...}
```

When you call `Print(new []\{"abc"\});` which method will be called? The first one, but it is not obvious. So we should avoid these overloads with default parameter values. 

Note there is this rule: https://msdn.microsoft.com/en-us/library/ms182135.aspx, CA1026, saying that optional parameters should be avoided altogether because of CLS (non-)compliance. But I wouldn't go this far as optional parameters are really useful if you use named parameters in the calls: http://codeblog.jonskeet.uk/2015/06/03/backwards-compatibility-is-still-hard/

R# ID: *MethodOverloadWithOptionalParameter*

This rule could be covered by the http://jira.sonarsource.com/browse/RSPEC-3220, which covers overloads with `params` argument.

Implements http://jira.sonarsource.com/browse/RSPEC-3220

**Comment by tvsonar** [comment]
Duplicates #58
