### ISSUE TITLE
type.IsInstanceOfType(type) doesn't make any sense

### ISSUE THREAD

**Issue by tvsonar** [SonarSource/sonarlint-vs#674]
R# _PossibleMistakenArgument_

Calling `IsInstanceOfType` with a type argument rarely makes sense.
```C#
    var type = typeof (string);
    var isInstance = type.IsInstanceOfType(type); //Noncompliant, false
```
it's only going to be true, if the type is `typeof(System.Type)`. Maybe `IsAssignableFrom` was meant, or simply not `type` as an argument.

**Comment by ganncamp** [comment]
to be covered in https://github.com/SonarSource/sonarlint-vs/issues/675
