### ISSUE TITLE
Rule: Redundant parentheses should not be used

### ISSUE THREAD

**Issue by dbolkensteyn** [SonarSource/sonarlint-vs#68]
Replaces http://jira.sonarsource.com/browse/LINTVS-177

In C# when you call a constructor, you can specify property values as well for the initialized object:
`new SomeClass(1,2,3) \{ Property1 = 5, Property2 = 15\}`

But if there is no constructor argument this looks like the following:
`new SomeClass() \{ Property1 = 5, Property2 = 15\}`, where `()` is not needed so could be simplified to `new SomeClass \{ Property1 = 5, Property2 = 15\}`

R# ID: *RedundantEmptyObjectCreationArgumentList*

Implements http://jira.sonarsource.com/browse/RSPEC-3235

**Comment by tvsonar** [comment]
Duplicates #79
