### ISSUE TITLE
SonarLint.Rules.CSharp.InvocationResolvesToOverrideWithParams threw and Exception

### ISSUE THREAD

**Issue by huserben** [SonarSource/sonarlint-vs#729]
Hi there

I recently upgraded from SonarLint version 1.0.4 to 1.0.6. Since then, everytime I rebuild my solution, I get some "warnings" that result from an exception within the anaylzer as it seems:
![sonarlintexception](https://cloud.githubusercontent.com/assets/5486874/11812249/1d79f4fe-a33b-11e5-893d-6bac791577c3.PNG)

The solution we have is quite big and contains more than 150 projects, but we don't get an exception for every project.
I don't know if something during the upgrade went wrong and messed up some of the projects or if it is some kind of internal error. I did some research on these projects and I did not see any difference to the ones where it does not throw the exception...

Edit: After a quick look into the code, it seems that the rule S3220 causes the exception. After disabling the rule, I got rid of the exceptions (which works as a workaround for now...)

Regards

**Comment by dbolkensteyn** [comment]
Thanks @huserben for reporting this - we in fact already are aware of this issue, and it's currently being tracked by issue #714 scheduled to be fixed in SonarLint VS 1.7.0.
