### ISSUE TITLE
Rule: Parentheses are redundant if attribute has no arguments

### ISSUE THREAD

**Issue by dbolkensteyn** [SonarSource/sonarlint-vs#79]
Replaces http://jira.sonarsource.com/browse/LINTVS-195

Attribute instantiation is like a constructor call with arguments and property setters. But if there are no arguments passed, the parentheses can be omitted. 

```
[MyAnnotation()] //Noncompliant
public class X
{
}
```
is equivalent to
```
[MyAnnotation] //Noncompliant
public class X
{
}
```

R# ID: *RedundantAttributeParentheses*

Implements http://jira.sonarsource.com/browse/RSPEC-3235

**Comment by tvsonar** [comment]
Duplicates #68
