### ISSUE TITLE
Rule: Access to a static member of a type via a derived type

### ISSUE THREAD

**Issue by dbolkensteyn** [SonarSource/sonarlint-vs#80]
Replaces http://jira.sonarsource.com/browse/LINTVS-198

R# site: https://confluence.jetbrains.com/display/ReSharper/Access+to+a+static+member+of+a+type+via+a+derived+type

maintainability
confusing
major

R# ID: *AccessToStaticMemberViaDerivedType*

Implements http://jira.sonarsource.com/browse/RSPEC-3252

**Comment by dbolkensteyn** [comment]
@ganncamp : @tvsonar  I think http://jira.sonarsource.com/browse/RSPEC-2209 is relevant here. Can you confirm?

**Comment by dbolkensteyn** [comment]
@tvsonar : @ganncamp This is slightly different:
```
class A
{ 
  public static int Count = 0;
}
class B : A
{ 
}
...
B.Count = 10; //Noncompliant, should be A.Count
```

There are two issues with accessing `Count` through `B`:
* to the reader it might seem like we have two `Count` fields, which is not the case
* if `A` and `B` are defined in two separate DLLs, then in the project where you have `B.Count = 10;`, you need to reference both DLLs, and not just a.dll.

**Comment by tvsonar** [comment]
This rule is handled by Visual Studio. Its diagnostic ID is IDE0001.
