### ISSUE TITLE
Do not report issues on *.g.cs or other generated filenames

### ISSUE THREAD

**Issue by tvsonar** [SonarSource/sonarlint-vs#85]
Roslyn should ideally handle the reporting of issues on generated code out of the box, but this is not yet the case:
* https://github.com/dotnet/roslyn/issues/3940
* https://github.com/dotnet/roslyn/issues/1751

A very common scenario is `*.Designer.cs` files - which are generated by Visual Studio for Windows Form files for example.

With this issue, we want to exclude any file name containing (case insensitively):
* .g.
* .generated.
* .designer.
* TemporaryGeneratedFile_

This issue relates to #164

**Comment by dbolkensteyn** [comment]
Also have a look at http://geekswithblogs.net/terje/archive/2008/11/10/hiding-generated-code-from-code-analysis-metrics-and-test-coverage.aspx

**Comment by dbolkensteyn** [comment]
What other tools are doing:

So at the moment everyone is implementing their own logic to do the filtering:
* https://github.com/DotNetAnalyzers/StyleCopAnalyzers/commit/823a4c07c91b63a575d4f7f7f395c5094dd1ab63
* https://github.com/code-cracker/code-cracker/blob/77ada1021fc0d7121c4011665ac8402e003ea9f5/src/CSharp/CodeCracker/Extensions/CSharpGeneratedCodeAnalysisExtensions.cs
* https://github.com/DustinCampbell/CSharpEssentials/commit/3ba72c08b99dfe95b68c7339162f08b61f3ec417
* https://github.com/icsharpcode/RefactoringEssentials/commit/21b7ecf3e329a7484c7339b3e5a8b3e97e43183c

It would also be nice to incorporate the "Suppress results from generated code" option from the Code Analysis project settings. But that only seems to be an FxCop flag.

**Comment by dbolkensteyn** [comment]
Issue updated as discussed
