### ISSUE TITLE
Rule S2197 should not report on unsigned values

### ISSUE THREAD

**Issue by tvsonar** [SonarSource/sonarlint-vs#86]
The rule "Modulus results should not be checked for direct equality" says that the result of a modulus can be negative. But this is not the case for unsigned values.

**Comment by dbolkensteyn** [comment]
@tvsonar you can proceed with the fix - the RSPEC is now clear http://jira.sonarsource.com/browse/RSPEC-2197

**Comment by dbolkensteyn** [comment]
btw let's not in the future implement rules in C# that are not enabled by default - it is costly to implement & maintain a rule - and I don't see a ROI to do that for a rule that cannot even be enabled by default in the end.
