### ISSUE TITLE
False positive on Rule S125 (commented out code)

### ISSUE THREAD

**Issue by jmecosta** [SonarSource/sonarlint-vs#89]
// does *not* overwrite file if (still) exists
Remove this commented out code. 
13 minutes ago   L262  
 Major    Open   Not planned   5min debt  Comment
 misra, unused

**Comment by dbolkensteyn** [comment]
thank you for the feedback @jmecosta - bug scheduled for the current sprint

**Comment by dbolkensteyn** [comment]
LGTM - but see comment
